# Generated by Django 2.1.3 on 2018-11-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=50)),
                ('site', models.CharField(blank=True, max_length=100)),
                ('nps', models.IntegerField()),
                ('service', models.IntegerField()),
                ('cleanliness', models.IntegerField()),
                ('checkin', models.IntegerField()),
                ('dinnerqual', models.IntegerField()),
                ('dinnerservice', models.IntegerField()),
                ('breakfastqual', models.IntegerField()),
                ('breakfastservice', models.IntegerField()),
                ('tmexceed', models.BooleanField()),
                ('tmexceeddetails', models.TextField(blank=True, max_length=1000)),
                ('anyfeedback', models.TextField(blank=True, max_length=2500)),
            ],
        ),
    ]
