# Generated by Django 2.1.3 on 2018-11-14 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='date_submitted',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
