# Generated by Django 2.1.3 on 2018-11-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_survey_arrival_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='email',
            field=models.EmailField(default='bob@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
